version: '3.9'

services:
#  db:
#    image: postgres
#    environment:
#      POSTGRES_USER: myuser
#      POSTGRES_PASSWORD: mypassword
#      POSTGRES_DB: mydb

  backend:
    container_name: backend
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
#    depends_on:
#      db:
#        condition: service_healthy

#  db:
#    image: mysql:5.7
#    ports:
#      - '3306:3306'
#    environment:
#      MYSQL_DATABASE: 'db_django'
#      MYSQL_USER: 'root'
#      MYSQL_PASSWORD: 'password'
#      MYSQL_ROOT_PASSWORD: 'password'
##    restart: always
##    volumes:
##      - ./db_django:/var/lib/mysql
#
#    healthcheck:
#      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
#      timeout: 5s
#      retries: 50